# Database configuration details
db:
  uri_env_key: "MONGO_URI"  
  database: "network_security"  
  collection: "intrusion_records"  

# File paths for storing datasets and intermediate artifacts
file_paths:
  raw_data: "artifacts/data_ingestion/raw_data.csv"  
  feature_store: "artifacts/feature_store/clean_data.csv"  
  train_data: "artifacts/train_test_split/train.csv" 
  test_data: "artifacts/train_test_split/test.csv"  

# Data validation configuration
validation:
  schema_file: "config/schema.yaml"  
  valid_train_file_path: "artifacts/data_validation/train_valid.csv"
  valid_test_file_path: "artifacts/data_validation/test_valid.csv"
  report_file: "artifacts/data_validation/validation_report.json" 
  drift_threshold: 0.05 

# Data transformation configuration
transformation:
  transformed_train_data: "artifacts/data_transformation/transformed_train.npy"  
  transformed_test_data: "artifacts/data_transformation/transformed_test.npy"  
  transformer_object: "artifacts/data_transformation/transformer.pkl"
  target_object: "artifacts/data_transformation/target_encoder.pkl"

# Model training parameters and output paths
training:
  test_size: 0.2  
  random_state: 42  
  model_output: "artifacts/model_training/model.pkl"  
  metrics_output: "artifacts/model_training/metrics.json" 
  target_columns: "Label" 

# Model evaluation output path
evaluation:
  evaluation_report: "artifacts/model_evaluation/evaluation_report.json"  
